// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4rXxBksszZ9OgV9MxwwXjqoqG7YE-v1I',
    appId: '1:26143845928:web:d7cbe38e24979a12d40f1d',
    messagingSenderId: '26143845928',
    projectId: 'chat-app-44665',
    authDomain: 'chat-app-44665.firebaseapp.com',
    storageBucket: 'chat-app-44665.appspot.com',
    measurementId: 'G-HHDVRQCLSR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmJ-v8HLoUR9VGyK_-Di_gJW1SYiDZs18',
    appId: '1:26143845928:android:66e3efc406e7e8f6d40f1d',
    messagingSenderId: '26143845928',
    projectId: 'chat-app-44665',
    storageBucket: 'chat-app-44665.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRdMdzAlb_nROih3hzPE65euHybQjqURc',
    appId: '1:26143845928:ios:da576839ae8e8f8ed40f1d',
    messagingSenderId: '26143845928',
    projectId: 'chat-app-44665',
    storageBucket: 'chat-app-44665.appspot.com',
    iosClientId:
        '26143845928-21cqghttg48itrvlechmgh9t2tr59nkg.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRdMdzAlb_nROih3hzPE65euHybQjqURc',
    appId: '1:26143845928:ios:da576839ae8e8f8ed40f1d',
    messagingSenderId: '26143845928',
    projectId: 'chat-app-44665',
    storageBucket: 'chat-app-44665.appspot.com',
    iosClientId:
        '26143845928-21cqghttg48itrvlechmgh9t2tr59nkg.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
